const fs = require('node:fs');
const path = require('node:path');
const target = path.join(__dirname, '../QuickAdd/audit_library.js');
let source = fs.readFileSync(target, 'utf8');
source = source.replace('    const { Notice, normalizePath } = obsidian;', `    const { Notice, normalizePath } = obsidian;
    const normalizeRequested = params.variables?.bookNormalize === true;
    const coreFile = app.vault.getAbstractFileByPath("Книги/_system/book_core.js");
    if (!coreFile) throw new Error("Не найден общий модуль библиотеки.");
    const coreModule = { exports: {} };
    new Function("module", await app.vault.read(coreFile))(coreModule);
    const core = coreModule.exports({ app, obsidian });`);
source = source.replace(/    function getFrontmatter\(file\) \{[\s\S]*?\n    \}/, '    const getFrontmatter = core.getFrontmatter;');
source = source.replace(/    function isCandidateBook\(file\) \{[\s\S]*?\n    \}/, '    const isCandidateBook = core.isCandidateBook;');
source = source.replace(/    function isFiction\(file\) \{[\s\S]*?\n    \}/, '    const isFiction = core.isFiction;');
source = source.replace('if (authorNormalizationGroups.length && quickAddApi)', 'if (normalizeRequested && authorNormalizationGroups.length && quickAddApi)');
source = source.replace('if (seriesNormalizationGroups.length && quickAddApi)', 'if (normalizeRequested && seriesNormalizationGroups.length && quickAddApi)');
source = source.replace('            frontmatter.authors = deduped;', `            frontmatter.authors = [...new Set(rawListValues(frontmatter.authors).map(author => memberSet.has(author) ? canonical : author))];`);
source = source.replace('            changedFiles++;\n        }\n\n        return { changedFiles, replacements, variantChanges };', '            await core.refreshFrontmatter(file);\n            changedFiles++;\n        }\n\n        return { changedFiles, replacements, variantChanges };');
source = source.replace('                frontmatter.series = canonical;', '                if (memberSet.has(asText(frontmatter.series))) frontmatter.series = canonical;');
source = source.replace('            changedFiles++;\n            variantChanges.set(current', '            await core.refreshFrontmatter(file);\n            changedFiles++;\n            variantChanges.set(current');
source = source.replace('await new Promise(resolve => setTimeout(resolve, 250));', 'await Promise.all(books.map(file => core.refreshFrontmatter(file)));');
source = source.replace('    const authorNormalizationGroups = buildAuthorNormalizationGroups(authorVariantStatsBefore);', `    const authorNormalizationGroups = buildAuthorNormalizationGroups(authorVariantStatsBefore);
    if (!normalizeRequested) for (const members of authorNormalizationGroups) warnings.push("Похожие варианты авторов: **" + members.join(" / ") + "**. Проверь отдельной командой «Нормализовать библиотеку».");`);
source = source.replace('    const seriesNormalizationGroups = buildSeriesNormalizationGroups(seriesVariantStatsBefore);', `    const seriesNormalizationGroups = buildSeriesNormalizationGroups(seriesVariantStatsBefore);
    if (!normalizeRequested) for (const members of seriesNormalizationGroups) warnings.push("Похожие варианты серий: **" + members.join(" / ") + "**. Проверь отдельной командой «Нормализовать библиотеку».");`);
source = source.replace('Аудит сам не исправляет ошибки, кроме подтвержденной тобой нормализации авторов/серий. Для однозначных исправлений используй ссылку «Исправить безопасное».', 'Проверка обновляет только этот отчёт. Нормализация авторов и серий запускается отдельной командой; однозначные исправления — ссылкой «Исправить».');
source = source.replace('    report += `> Последняя проверка:', '    report += `[🔧 Нормализовать](obsidian://quickadd?choice=${encodeURIComponent("Книги - Нормализовать библиотеку")})\\n\\n`;\n    report += `> Последняя проверка:');
source = source.replace(' — возможно, это экранизация.', ' — совпадение названий, требуется проверка первоисточника.');
const statsStart = source.indexOf('    // Обновляем компактную статистику на главной');
const statsEnd = source.indexOf('    new Notice(`Проверка завершена:', statsStart);
source = source.slice(0, statsStart) + `    const reportFile = await core.writeIfChanged(normalizePath(REPORT_PATH), report);

` + source.slice(statsEnd);
source = source.replace('- варианты и похожие написания авторов с предложением объединить их;', '- варианты и похожие написания авторов; объединение — отдельной командой;');
source = source.replace('- варианты и похожие написания серий с предложением объединить их;', '- варианты и похожие написания серий; объединение — отдельной командой;');
source = source.replace('        const current = await app.vault.read(file);\n        await app.vault.modify(file, current.replace(/\\s*$/, "\\n\\n") + block);', '        await app.vault.process(file, current => current.replace(/\\s*$/, "\\n\\n") + block);');
fs.writeFileSync(target, source);
